addr: 127.0.0.1:9999
sms_file: sms.data
mms_addr: http://127.0.0.1:9999/mms
mms_file: mms.json
voice_call_file: voice.data
email_file: email.data
billing_file: billing.data
support_addr: http://127.0.0.1:9999/support
support_file: support.json
incident_addr: http://127.0.0.1:9999/incident
incident_file: incident.json
web_dir: web